export const Sources = {
    203: {
        id: 203,
        name: 'Netflix',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/netflix_100px.png',
        ios_appstore_url: 'http://itunes.apple.com/app/netflix/id363590051',
        android_playstore_url:
            'https://play.google.com/store/apps/details?id=com.netflix.mediaclient&hl=en',
        android_scheme: 'nflx',
        ios_scheme: 'nflx',
        regions: [
            'US',
            'CA',
            'GB',
            'AU',
            'BR',
            'AR',
            'BE',
            'BG',
            'CH',
            'CL',
            'CO',
            'CZ',
            'DE',
            'DK',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GR',
            'HK',
            'HR',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'JP',
            'KR',
            'LT',
            'MX',
            'MY',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'RO',
            'RS',
            'RU',
            'SE',
            'SG',
            'TH',
            'TR',
            'UA',
            'VN',
            'ZA',
            'ar',
            'ch',
            'cl',
            'co',
            'ec',
            'ee',
            'fr',
            'gr',
            'id',
            'jp',
            'kr',
            'lt',
            'mx',
            'my',
            'pe',
            'ph',
            'sg',
            'th',
            'tr',
            'vn',
            'za',
        ],
    },
    157: {
        id: 157,
        name: 'Hulu',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/hulu_100px.png',
        ios_appstore_url: 'http://itunes.apple.com/app/hulu-plus/id376510438',
        android_playstore_url:
            'https://play.google.com/store/apps/details?id=com.hulu.plus',
        android_scheme: 'hulu',
        ios_scheme: 'hulu',
        regions: ['US'],
    },
    26: {
        id: 26,
        name: 'Amazon Prime',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/prime_video_100px.png',
        ios_appstore_url: 'http://itunes.apple.com/app/amazon-instant-video/id545519333',
        android_playstore_url: 'http://amazon.com/GetAndroidVideo',
        android_scheme: 'intent',
        ios_scheme: 'aiv',
        regions: [
            'AR',
            'CH',
            'CL',
            'CO',
            'EC',
            'FR',
            'MX',
            'PA',
            'PE',
            'US',
            'IE',
            'GB',
            'ES',
            'NZ',
            'ZA',
            'DE',
            'HK',
            'ID',
            'IN',
            'MY',
            'PH',
            'PT',
            'TH',
            'VN',
            'RO',
            'BE',
            'IL',
            'KR',
            'RU',
            'DK',
            'FI',
            'IS',
            'NO',
            'SE',
            'PL',
            'NL',
            'SG',
            'HU',
            'BG',
            'CZ',
            'EE',
            'GR',
            'HR',
            'LT',
            'RS',
            'TR',
            'UA',
            'BR',
            'JP',
            'CA',
            'AU',
            'be',
            'dk',
            'fi',
            'in',
            'nl',
            'no',
            'se',
        ],
    },
    387: {
        id: 387,
        name: 'HBO MAX',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/hbomax_100px.png',
        ios_appstore_url: null,
        android_playstore_url: null,
        android_scheme: 'hbomax',
        ios_scheme: 'hbomax',
        regions: ['US', 'AR', 'CL', 'CO', 'EC', 'MX', 'PE', 'BR'],
    },
    372: {
        id: 372,
        name: 'Disney+',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/disneyPlus_100px.png',
        ios_appstore_url: 'https://apps.apple.com/app/disney/id1446075923',
        android_playstore_url: null,
        android_scheme: 'disneyplus',
        ios_scheme: 'disneyplus',
        regions: [
            'FR',
            'US',
            'CA',
            'GB',
            'AU',
            'BR',
            'AR',
            'BE',
            'CH',
            'CL',
            'CO',
            'DE',
            'DK',
            'ES',
            'FI',
            'MX',
            'NL',
            'NO',
            'NZ',
            'PT',
            'SE',
        ],
    },
    371: {
        id: 371,
        name: 'AppleTV+',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/appleTvPlus_100px.png',
        ios_appstore_url: null,
        android_playstore_url: null,
        android_scheme: null,
        ios_scheme: null,
        regions: [
            'US',
            'CA',
            'GB',
            'AU',
            'BR',
            'AR',
            'BE',
            'BG',
            'CH',
            'CL',
            'CO',
            'CZ',
            'DE',
            'DK',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GR',
            'HK',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'JP',
            'KR',
            'LT',
            'MX',
            'MY',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'RU',
            'SE',
            'SG',
            'TH',
            'UA',
            'VN',
            'ZA',
        ],
    },
    444: {
        id: 444,
        name: 'Paramount+',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/paramountPlus_100px.png',
        ios_appstore_url: null,
        android_playstore_url: null,
        android_scheme: 'pplus',
        ios_scheme: 'cbs',
        regions: ['US', 'AU', 'BR', 'CA'],
    },
    388: {
        id: 388,
        name: 'Peacock',
        type: 'free',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/peacock_100px.png',
        ios_appstore_url: null,
        android_playstore_url: null,
        android_scheme: 'peacock',
        ios_scheme: 'peacock',
        regions: ['US'],
    },
    389: {
        id: 389,
        name: 'Peacock Premium',
        type: 'sub',
        logo_100px: 'https://cdn.watchmode.com/provider_logos/peacockPremium_100px.png',
        ios_appstore_url: null,
        android_playstore_url: null,
        android_scheme: 'peacock',
        ios_scheme: 'peacock',
        regions: ['US'],
    },

    // extra sources
    // {
    //     id: 385,
    //     name: 'HBO (Via Hulu)',
    //     type: 'sub',
    //     logo_100px: 'https://cdn.watchmode.com/provider_logos/385_autogenerated.png',
    //     ios_appstore_url: null,
    //     android_playstore_url: null,
    //     android_scheme: 'hulu',
    //     ios_scheme: 'hulu',
    //     regions: ['US'],
    // },
};
